**A command line, or terminal:** is a text based interface to the system. You are able to enter commands by typing them on the keyboard.
The command line typically presents you with a ""prompt"". As you type, it will be displayed after the prompt.

**For example:**
- user@bash: ls -l/home/ryan is presented after we entered a command (ls).

- Another command is ""pwd"" which stands for Print Working Directory, this command shows you what your
  current working diectory is.

theme: jekyll-theme-leap-day